Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheAftermath_V2.Models;

namespace TheAftermath_V2.Controllers
{
    public class GamesController : Controller
    {
        public AftermathDBEntities db = new AftermathDBEntities();

        // -- ADMIN PAGE -- //
        public ActionResult Admin()
        {
            if (Session["Active"] != null)
            {
                Guid acctID = Guid.Parse(Session["UserID"].ToString());
                string gamename = HttpContext.Request.QueryString["campaign"];
                var game = db.Campaigns.Where(a => a.Name == gamename).First();
                //game.Locked = true;
                db.SaveChanges();

                // GET CURRENT VALUES
                var gameData = new Classes.GameData
                {
                    Name = game.Name,
                    Season = game.Season,
                    Year = game.Year,
                    Description = game.Description,
                    PlayerPassword = game.PlayerPassword,
                    AdminPassword = game.AdminPassword
                };

                return View(gameData);
            }
            else return RedirectToAction("Login", "Home");

        }
        // -- ADMIN SUBMIT -- //
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Admin([Bind(Include = "Name, Season, Year, Description, PlayerPassword, AdminPassword, Closed")] Classes.GameData input)
        {
            if (ModelState.IsValid)
            {
                var game = db.Campaigns.Where(a => a.Name == input.Name).FirstOrDefault();
                game.Name = input.Name;
                game.Season = input.Season;
                game.Year = input.Year;
                game.Description = input.Description;
                game.Locked = false;
                game.PlayerPassword = input.PlayerPassword;
                game.AdminPassword = input.AdminPassword;
                game.Closed = input.Closed;
                db.SaveChanges();

                ViewBag.ErrorMessage = "Success";
                return RedirectToAction("Success", "Home");
            }
            else return View(input); 
        }

        [HttpPost]
        public JsonResult CheckGameName(string gamename)
        {
            bool isValid = !db.Campaigns.ToList().Exists(a => a.Name.Equals(gamename, StringComparison.CurrentCultureIgnoreCase));
            return Json(isValid);
        }

        [HttpPost]
        public JsonResult GetCharacterList(string game)
        {
            Guid gameID = db.Campaigns.Where(a => a.Name == game).Select(a => a.ID).First();

            var characterQ = from ax in db.AccountStatus
                             where ax.CampaignID == gameID
                             join a in db.Accounts on ax.AccountID equals a.ID
                             join c in db.Characters on ax.CharacterID equals c.ID
                             select new { a.Username, ax.CharacterID, c.Name, c.Sex };

            List<Classes.UserData> characterList = new List<Classes.UserData>();
            foreach (var record in characterQ)
            {
                characterList.Add(new Classes.UserData { Username = record.Username, CharacterID = (Guid)record.CharacterID, CharacterName = record.Name, CharacterSex = record.Sex });
            }
            return Json(characterList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetCharacterSheet(string name, string user)
        {
            Guid acctID = db.Accounts.Where(a => a.Username == user).Select(a => a.ID).Single();

            var character = db.Characters.Where(a => a.Name == name && a.AccountID == acctID).First();
            var charAttrs = db.CharacterAttributes.Where(a => a.CharacterID == character.ID).Join(db.Attributes, ca => ca.AttributeID, a => a.ID, (ca, a) => new { Name = a.Name, Value = ca.Value });

            var skillQuery = from cs in db.CharacterSkills
                             where cs.CharacterID == character.ID
                             join s in db.Skills on cs.SkillID equals s.ID
                             select new { s.Name, s.Type, s.Class, cs.Value };

            List<Classes.SkillData> skillList = new List<Classes.SkillData>();
            foreach (var skill in skillQuery) skillList.Add(new Classes.SkillData { Name = skill.Name, Type = skill.Type, Class = skill.Class, Value = skill.Value });

            var abilityQuery = from ca in db.CharacterAbilities
                               where ca.CharacterID == character.ID
                               join a in db.Abilities on ca.AbilityID equals a.ID
                               select new { a.Name, a.Description };

            Classes.IDMarks idMarks = new Classes.IDMarks
            {
                EyeColor = db.IDMarks.Where(a => a.CharacterID == character.ID).Select(a=>a.EyeColor).SingleOrDefault(),
                HairColor = db.IDMarks.Where(a => a.CharacterID == character.ID).Select(a => a.HairColor).SingleOrDefault(),
                HairStyle = db.IDMarks.Where(a => a.CharacterID == character.ID).Select(a => a.HairStyle).SingleOrDefault(),
                FacialHair = db.IDMarks.Where(a => a.CharacterID == character.ID).Select(a => a.FacialHair).SingleOrDefault()
            };

            List<Classes.AbilityData> abilityList = new List<Classes.AbilityData>();
            foreach (var ability in abilityQuery) abilityList.Add(new Classes.AbilityData { Name = ability.Name, Description = ability.Description });

            Classes.CharacterData charData = new Classes.CharacterData
            {
                // DEMOGRAPHICS
                Name = character.Name,
                Status = character.Status,
                Birthdate = character.Birthdate,
                Sex = character.Sex,
                Ethnicity = character.Ethnicity,
                Habitat = character.Habitat,
                History = db.Histories.Where(a => a.ID == character.History).Select(a => a.Name).First(),
                Strategy = character.Strategy,
                Background = db.Backgrounds.Where(a => a.ID == character.Background).Select(a => a.Name).First(),

                // ATTRIBUTES
                Memory = charAttrs.Where(a => a.Name == "Memory").Select(a => a.Value).First(),
                Logic = charAttrs.Where(a => a.Name == "Logic").Select(a => a.Value).First(),
                Perception = charAttrs.Where(a => a.Name == "Perception").Select(a => a.Value).First(),
                Willpower = charAttrs.Where(a => a.Name == "Willpower").Select(a => a.Value).First(),
                Charisma = charAttrs.Where(a => a.Name == "Charisma").Select(a => a.Value).First(),

                Strength = charAttrs.Where(a => a.Name == "Strength").Select(a => a.Value).First(),
                Endurance = charAttrs.Where(a => a.Name == "Endurance").Select(a => a.Value).First(),
                Agility = charAttrs.Where(a => a.Name == "Agility").Select(a => a.Value).First(),
                Speed = charAttrs.Where(a => a.Name == "Speed").Select(a => a.Value).First(),
                Beauty = charAttrs.Where(a => a.Name == "Beauty").Select(a => a.Value).First(),

                Skills = skillList,
                Abilities = abilityList,
                IDMarks = idMarks
            };

            return Json(charData, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetExperience(string user, string charname)
        {
            Guid acctID = db.Accounts.Where(a => a.Username == user).Select(a => a.ID).Single();
            Guid charID = db.Characters.Where(a => a.Name == charname && a.AccountID == acctID).Select(a => a.ID).Single();
            int exp = db.CharacterExps.Where(a => a.CharacterID == charID).Select(a => a.AvailableExp).Single();

            return Json(exp, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetGameActiveList(string game)
        {
            Guid gameID = db.Campaigns.Where(a => a.Name == game).Select(a => a.ID).First();

            var activeQ = from ax in db.AccountStatus
                          where ax.CampaignID == gameID
                          join a in db.Accounts on ax.AccountID equals a.ID
                          select new { a.Username, ax.Play, ax.Tell };

            List<Classes.UserData> userList = new List<Classes.UserData>();
            foreach (var record in activeQ)
            {
                userList.Add(new Classes.UserData { Username = record.Username, Play = record.Play, Tell = record.Tell });
            }

            return Json(userList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetGameData(string name)
        {
            var gameQ = (from c in db.Campaigns
                         where c.Name == name && c.Closed == false
                         select new { c.Season, c.Year, c.Description }).Single();

            Classes.GameData result = new Classes.GameData
            {
                Season = gameQ.Season,
                Year = gameQ.Year,
                Description = gameQ.Description
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetGameLinks(string game)
        {
            var gameRecord = db.Campaigns.Where(a => a.Name == game).Single();
            Campaign result = new Campaign
            {
                ConferenceLink = gameRecord.ConferenceLink,
                MapLoc = gameRecord.MapLoc,
                PictureLoc = gameRecord.PictureLoc
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetGamePW(Guid ID)
        {
            var gameQ = (from c in db.Campaigns
                         where c.ID == ID && c.Closed == false

Views/Games/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}
@model TheAftermath_V2.Classes.GameData

<script type="text/javascript">
    $(document).ready(function () {
        $('body').css('background-image', 'url("../Content/Images/Textures/darkRust.jpg")');
    });
</script>

<!-- MODALS -->
<!-- CONFIRM MODAL -->
<div class="modal fade" id="confirmModal" data-backdrop="static" tabindex="-2" aria-labelledby="confirmModalLabel" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h5 class="text-center font-weight-bold">ARE YOU CERTAIN YOU WANT TO CLOSE THIS CAMPAIGN?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" id="submitConfirmBtn" class="btn btn-lg btn-success border border-dark mx-auto">CONFIRM</button>
                <button type="button" id="cancelConfirmBtn" class="btn btn-lg btn-danger border border-dark mx-auto">CANCEL</button>
            </div>
        </div>
    </div>
</div>

<div id="IM-Modals"></div>

<!-- BEGIN FORM -->
@using (Html.BeginForm("Admin", "Games", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <!--CAMPAIGN NAME-->
    <div class="row bg-black mt-5 pt-3">
        <div class="col-md-3"></div>
        <div class="col-6 col-md-3">
            <img src="~/Content/Images/Graffiti/Campaign-Red-500x150.png" class="img-fluid mx-auto d-block" />
        </div>
        <div class="col-6 col-md-3">
            <div class="input-group my-2 text-center">
                <input name="Name" id="gameName" class="form-control text-center px-0 py-0 my-2 w-100" type="text" value="@Model.Name" />
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
    <!--SEASON-->
    <div class="row bg-black">
        <div class="col-md-3"></div>
        <div class="col-6 col-md-3">
            <img src="~/Content/Images/Graffiti/Season-black-500x150.png" class="img-fluid mx-auto d-block" />
        </div>
        <div class="col-6 col-md-3">
            <select name="Season" id="season" class="custom-select custom-select-lg mt-2 text-center w-100" value="@Model.Season">
                <option value="Spring">Spring</option>
                <option value="Summer">Summer</option>
                <option value="Fall">Fall</option>
                <option value="Winter">Winter</option>
            </select>
        </div>
        <div class="col-md-3"></div>
    </div>
    <!--YEAR-->
    <div class="row bg-black">
        <div class="col-md-3"></div>
        <div class="col-6 col-md-3">
            <img src="~/Content/Images/Graffiti/Year-black-500x150.png" class="img-fluid mx-auto d-block" />
        </div>
        <div class="col-6 col-md-3">
            <select name="Year" id="year" class="custom-select custom-select-lg mt-2 text-center w-100" value="@Model.Year">
                <option disabled>[Pre-Apocalypse]</option>
                <option value="2012">2012</option>
                <option disabled>[The Apocalypse]</option>
                <option value="2013">2013</option>
                <option value="2014">2014</option>
                <option value="2015">2015</option>
                <option value="2016">2016</option>
                <option value="2017">2017</option>
                <option disabled>[The Aftermath]</option>
                <option value="2018">2018</option>
                <option value="2019">2019</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option disabled>[Present Day]</option>
                <option value="2022">2022</option>
                <option value="2023">2023</option>
                <option value="2024">2024</option>
                <option value="2025">2025</option>
                <option value="2026">2026</option>
                <option value="2027">2027</option>
                <option value="2028">2028</option>
                <option value="2029">2029</option>
                <option value="2030">2030</option>
                <option value="2031">2031</option>
                <option value="2032">2032</option>
            </select>
        </div>
        <div class="col-md-3"></div>
    </div>
    <!--DESCRIPTION-->
    <div class="row bg-black">
        <div class="col-md-3"></div>
        <div class="col-6 col-md-3">
            <img src="~/Content/Images/Graffiti/description-white-500x150.png" class="img-fluid mx-auto d-block">
        </div>
        <div class="col-6 col-md-3">
            <textarea name="Description" id="description" rows="4" cols="50" class="rounded w-100">@Model.Description</textarea>
        </div>
        <div class="col-md-3"></div>
        <hr />
    </div>
    <!--PLAYER PW-->
    <div class="row bg-black">
        <div class="col-md-3"></div>
        <div class="col-6 col-md-3">
            <img src="~/Content/Images/Graffiti/PlayerPW-red-500x150.png" class="img-fluid mx-auto d-block">
        </div>
        <div class="col-6 col-md-3">
            <div class="input-group my-2 text-center">
                <input name="PlayerPassword" id="playerPW" class="form-control text-center px-0 py-0 my-2 w-100" type="text" value="@Model.PlayerPassword" placeholder="Grants Access to PLAY" />
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
    <!--CONFIRM PLAYER PW-->
    <div class="row bg-black">
        <div class="col-md-3"></div>
        <div class="col-6 col-md-3">
            <img src="~/Content/Images/Graffiti/ConfirmPW-white-500x150.png" class="img-fluid mx-auto d-block">
        </div>
        <div class="col-6 col-md-3">
            <div class="input-group my-2 text-center">
                <input id="confirmPlayerPW" class="form-control text-center px-0 py-0 my-2 w-100" type="text" value="@Model.PlayerPassword" />
            </div>
        </div>
        <div class="col-md-3"></div>
        <hr />
    </div>
    <!--STORYTELLER PW-->
    <div class="row bg-black">
        <div class="col-md-3"></div>
        <div class="col-6 col-md-3">
            <img src="~/Content/Images/Graffiti/StorytellerPW-green-500x150.png" class="img-fluid mx-auto d-block">
        </div>
        <div class="col-6 col-md-3">
            <div class="input-group my-2 text-center">
                <input name="AdminPassword" id="storytellerPW" class="form-control text-center px-0 py-0 my-2 w-100" type="text" value="@Model.AdminPassword" placeholder="Grants Access to TELL / ADMIN" />
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
    <!--CONFIRM STORYTELLER PW-->
    <div class="row bg-black">
        <div class="col-md-3"></div>
        <div class="col-6 col-md-3">
            <img src="~/Content/Images/Graffiti/ConfirmPW-white-500x150.png" class="img-fluid mx-auto d-block">
        </div>
        <div class="col-6 col-md-3">
            <div class="input-group my-2 text-center">
                <input id="confirmStorytellerPW" class="form-control text-center px-0 py-0 my-2 w-100" type="text" value="@Model.AdminPassword" />
            </div>
        </div>
        <div class="col-md-3"></div>
        <hr />
    </div>
    <!--END GAME-->
    <div class="row bg-black pt-3">
        <div class="col-4"></div>
        <div class="col-4">
            <select name="Closed" id="gateway" class="custom-select custom-select-lg my-2 text-center w-100" value="@Model.Closed">
                <option value="False" selected="selected">OPEN</option>
                <option value="True">CLOSED</option>
            </select>
        </div>
        <div class="col-4"></div>
    </div>
    <!--SUBMIT-->
    <div class="row bg-black pb-3">
        <div class="col-4"></div>
        <div class="col-4">
            <input id="submitBtn" class="btn btn-lg btn-success border border-light mx-auto btn-block mb-3" type="submit" value="SUBMIT" />
        </div>
        <div class="col-4"></div>
    </div>
}

@section Scripts
{
    <script src="@Url.Content("~/Scripts/jquery.signalR-2.4.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Custom/SignalR-IM.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/signalr/hubs")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Custom/GameAdmin.js")" type="text/javascript"></script>
}

Views/Games/Index.cshtml
@{
    ViewBag.Title = "Campaigns";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('body').css('background-image', 'url("../Content/Images/Textures/darkRust.jpg")');
    });
</script>

<!-- MODALS -->
<!-- PASSWORD MODAL -->
<div class="modal fade" id="passwordModal" data-backdrop="static" tabindex="-1" aria-labelledby="passwordModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header bg-light">
                <h5 class="font-weight-bold mx-auto text-uppercase gameHeader"></h5>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row bg-black h-15 justify-content-md-center">
                        <div class="col-6 col-md-4">
                            <img src="~/Content/Images/Graffiti/passwordWhite-500x150.png" class="img-fluid mx-auto d-block mh-10" />
                        </div>
                        <div class="col-6 col-md-4">
                            <div class="input-group input-group-lg">
                                <input class="form-control text-center px-0 py-0 my-4" type="password" id="passwordInput" value="" />
                            </div>
                        </div>
                    </div>
                    <div class="row bg-black">
                        <h4 id="errorMsg" class="mx-auto font-weight-bold text-red d-none"></h4>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lg btn-success border border-dark mx-auto submitBtn" data-target="" data-id="">SUBMIT</button>
                <button type="button" class="btn btn-lg btn-danger border border-dark mx-auto cancelBtn" data-dismiss="modal">CANCEL</button>
            </div>
        </div>
    </div>
</div>
<!-- CHARACTER SELECT MODAL -->
<div class="modal fade" id="charSelectModal" data-backdrop="static" tabindex="-2" aria-labelledby="charSelectModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header bg-light">
                <h5 class="font-weight-bold mx-auto text-uppercase gameHeader"></h5>
            </div>
            <div class="modal-body bg-black">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="d-none d-lg-block col-lg-2">
                            <img src="~/Content/Images/Graffiti/name-black-500x150.png" class="img-fluid mx-auto d-block mh-5" />
                        </div>
                        <div class="d-none d-lg-block col-lg-2">
                            <img src="~/Content/Images/Graffiti/status-green-500x150.png" class="img-fluid mx-auto d-block mh-5" />
                        </div>
                        <div class="d-none d-lg-block col-lg-2">
                            <img src="~/Content/Images/Graffiti/background-white-500x150.png" class="img-fluid mx-auto d-block mh-5" />
                        </div>
                        <div class="d-none d-lg-block col-lg-2">
                            <img src="~/Content/Images/Graffiti/total-white-500x150.png" class="img-fluid mx-auto d-block mh-5" />
                        </div>
                        <div class="d-none d-lg-block col-lg-2">
                            <img src="~/Content/Images/Graffiti/exp-red-500x150.png" class="img-fluid mx-auto d-block mh-5" />
                        </div>
                        <div class="col-lg-1"></div>
                    </div>
                    <div class="bg-black" id="characterList"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lg btn-danger border border-dark mx-auto cancelBtn" data-dismiss="modal">CANCEL</button>
            </div>
        </div>
    </div>
</div>
<!-- DESCRIPTION MODAL -->
<div class="modal fade" id="descriptionModal" data-backdrop="static" tabindex="-3" aria-labelledby="descriptionModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header bg-light">
                <h5 class="font-weight-bold mx-auto text-uppercase modal-title gameHeader"></h5>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row bg-black pt-5">
                        <div class="col-lg-3"></div>
                        <div class="col-6 col-lg-3">
                            <img src="~/Content/Images/Graffiti/Season-black-500x150.png" class="img-fluid mx-auto d-block" />
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="input-group input-group-lg">
                                <input class="form-control text-center px-0 py-0 my-3" type="text" id="descSeason" value="" readonly />
                            </div>
                        </div>
                        <div class="col-lg-3"></div>
                    </div>

                    <div class="row bg-black">
                        <div class="col-lg-3"></div>
                        <div class="col-6 col-lg-3">
                            <img src="~/Content/Images/Graffiti/Year-black-500x150.png" class="img-fluid mx-auto d-block" />
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="input-group input-group-lg">
                                <input class="form-control text-center px-0 py-0 my-3" type="text" id="descYear" value="" readonly />
                            </div>
                        </div>
                        <div class="col-lg-3"></div>
                    </div>

                    <div class="row bg-black justify-content-md-around pb-5">
                        <div class="col-12 col-md-9">
                            <p id="descText" class="bg-white font-weight-bold w-100 h-33" readonly></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lg btn-danger border border-dark mx-auto cancelBtn" data-dismiss="modal">CANCEL</button>
            </div>
        </div>
    </div>
</div>

<div id="IM-Modals"></div>

<!-- PAGE START -->
<div class="row">
    <div class="col-12 col-md-9">
        <img src="~/Content/Images/Graffiti/campaigns-900x150.png" class="img-fluid mx-auto d-block h-15 my-2" />
    </div>
    <div class="col-3 d-md-none"></div>
    <div class="col-6 col-md-3">
        <a href="@Url.Action("NewGame", "Games")" class="btn btn-lg btn-red font-weight-bold border border-light rounded mx-auto btn-block my-md-5" type="button">NEW GAME</a>
    </div>
    <div class="col-3 d-md-none"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="d-none d-md-block col-md-2">
        <img src="~/Content/Images/Graffiti/Name-white-500x150.png" class="img-fluid mx-auto d-block mh-5" />
    </div>
    <div class="d-none d-md-block col-md-2">
        <img src="~/Content/Images/Graffiti/pop-white-500x150.png" class="img-fluid mx-auto d-block mh-5" />
    </div>
    <div class="d-none d-md-block col-md-2">
        <img src="~/Content/Images/Graffiti/description-white-500x150.png" class="img-fluid mx-auto d-block mh-5" />
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-2"></div>
</div>

<div id="gameList" class="bg-black my-2 px-2 border border-light rounded"></div>

@section Scripts
{
    <script src="@Url.Content("~/Scripts/jquery.signalR-2.4.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Custom/SignalR-IM.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/signalr/hubs")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Custom/GameSelect.js")" type="text/javascript"></script>
}